.DEFAULT_GOAL = test

# get path to the top level directory
TEST_FRAMEWORK_DIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
QMC_HEADERS_DIR = $(TEST_FRAMEWORK_DIR)/../../src

GCOV ?= gcov
GCOVFLAGS =

CXX ?= g++
CXXFLAGS += -std=c++11 -g -O0 -fprofile-arcs -ftest-coverage -I$(QMC_HEADERS_DIR) -I$(TEST_FRAMEWORK_DIR)
ifneq ($(CXX), nvcc)
LDFLAGS += -pthread
endif
LDFLAGS += $(TEST_FRAMEWORK_DIR)/catch.o -lm
